# Generated by Django 4.1.7 on 2023-08-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_auth_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
