# Generated by Django 4.1.7 on 2023-08-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_auth_service', '0002_admin_refresh_token_vendor_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='refresh_token',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='refresh_token',
            field=models.TextField(default=''),
        ),
    ]
