# Generated by Django 4.1.7 on 2023-08-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_auth_service', '0004_alter_admin_refresh_token_alter_vendor_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('verifiable_cred', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('otp', models.IntegerField(default=0)),
            ],
        ),
    ]
