# Generated by Django 4.1.7 on 2023-08-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_auth_service', '0006_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='email_verified_at',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='registered_at',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
