# Generated by Django 4.1.7 on 2023-08-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_auth_service', '0008_mailverify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
