# Generated by Django 4.1.7 on 2023-09-09 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('micro_brand_service', '0015_alter_brand_created_at_alter_brandroles_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.CharField(default=1694270667.892533, max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_branch', to='micro_brand_service.brand')),
            ],
        ),
        migrations.CreateModel(
            name='BranchMeta',
            fields=[
                ('branch_meta_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('postal_code', models.CharField(blank=True, max_length=6, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('district', models.CharField(blank=True, max_length=30, null=True)),
                ('address_1', models.CharField(blank=True, max_length=30, null=True)),
                ('address_2', models.CharField(blank=True, max_length=30, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_meta', to='micro_branch_service.branch')),
            ],
        ),
    ]
