# Generated by Django 4.1.7 on 2023-08-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_logo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrandRoles',
            fields=[
                ('user_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_roles', to='micro_brand_service.brand')),
            ],
        ),
    ]
