# Generated by Django 4.1.7 on 2023-08-22 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('micro_auth_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_logo', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.CharField(default=1692713511.877276, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BrandVerification',
            fields=[
                ('brand_verify_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('govt_doc', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_verification', to='micro_brand_service.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_brand_verify', to='micro_auth_service.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='BrandRoles',
            fields=[
                ('brand_roles_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.CharField(default=1692713511.881277, max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_role', to='micro_brand_service.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_brand_role', to='micro_auth_service.vendor')),
            ],
        ),
    ]
