# Generated by Django 4.1.7 on 2023-08-20 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('micro_brand_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BrandVerification',
            fields=[
                ('user_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('govt_doc', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_verification', to='micro_brand_service.brand')),
            ],
        ),
    ]
