# Generated by Django 4.1.7 on 2023-08-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_brand_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesBrand',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('role_desc', models.CharField(blank=True, max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.CharField(default=1692865723.471291, max_length=50),
        ),
        migrations.AlterField(
            model_name='brandroles',
            name='created_at',
            field=models.CharField(default=1692865723.47529, max_length=50),
        ),
    ]
