# Generated by Django 4.1.7 on 2023-08-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_brand_service', '0002_rolesbrand_alter_brand_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandverification',
            name='created_at',
            field=models.CharField(default=1692866238.147054, max_length=50),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.CharField(default=1692866238.143053, max_length=50),
        ),
        migrations.AlterField(
            model_name='brandroles',
            name='created_at',
            field=models.CharField(default=1692866238.148054, max_length=50),
        ),
    ]
