# Generated by Django 4.1.7 on 2023-08-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_brand_service', '0002_brand_is_verified_brandverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='created_at',
            field=models.CharField(default=1692543218.096031, max_length=50),
        ),
    ]
