# Generated by Django 4.1.7 on 2023-08-24 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('micro_auth_service', '0004_alter_admin_refresh_token_alter_vendor_refresh_token'),
        ('micro_brand_service', '0003_brandverification_created_at_alter_brand_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandroles',
            old_name='brand_roles_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.CharField(default=1692868028.249423, max_length=50),
        ),
        migrations.AlterField(
            model_name='brandroles',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brandroles_brand', to='micro_brand_service.brand'),
        ),
        migrations.AlterField(
            model_name='brandroles',
            name='created_at',
            field=models.CharField(default=1692868028.254424, max_length=50),
        ),
        migrations.AlterField(
            model_name='brandroles',
            name='role',
            field=models.ForeignKey(default='no role', on_delete=django.db.models.deletion.CASCADE, related_name='brandroles_role', to='micro_brand_service.rolesbrand'),
        ),
        migrations.AlterField(
            model_name='brandroles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brandroles_user', to='micro_auth_service.vendor'),
        ),
        migrations.AlterField(
            model_name='brandverification',
            name='created_at',
            field=models.CharField(default=1692868028.251423, max_length=50),
        ),
    ]
