# Generated by Django 4.1.7 on 2023-08-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_brand_service', '0003_brand_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandroles',
            name='created_at',
            field=models.CharField(default=1692543315.855306, max_length=50),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.CharField(default=1692543315.854308, max_length=50),
        ),
    ]
