# Generated by Django 4.1.7 on 2023-08-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_brand_service', '0004_brandroles_created_at_alter_brand_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.CharField(default=1692674567.14728, max_length=50),
        ),
        migrations.AlterField(
            model_name='brandroles',
            name='created_at',
            field=models.CharField(default=1692674567.148282, max_length=50),
        ),
    ]
