# Generated by Django 4.1.7 on 2023-08-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_brand_service', '0005_alter_brand_created_at_alter_brandroles_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.CharField(default=1692687552.901439, max_length=50),
        ),
        migrations.AlterField(
            model_name='brandroles',
            name='created_at',
            field=models.CharField(default=1692687552.901439, max_length=50),
        ),
    ]
