# Generated by Django 4.1.7 on 2023-08-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_brand_service', '0005_rename_govt_doc_brandverification_govt_doc_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.CharField(default=1692889991.065446, max_length=50),
        ),
        migrations.AlterField(
            model_name='brandroles',
            name='created_at',
            field=models.CharField(default=1692889991.14245, max_length=50),
        ),
        migrations.AlterField(
            model_name='brandverification',
            name='created_at',
            field=models.CharField(default=1692889991.115451, max_length=50),
        ),
    ]
