# Generated by Django 4.1.7 on 2023-08-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_brand_service', '0012_alter_brand_created_at_alter_brandroles_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RolesBrand',
            new_name='RolesForBrand',
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.CharField(default=1693230090.255143, max_length=50),
        ),
        migrations.AlterField(
            model_name='brandroles',
            name='created_at',
            field=models.CharField(default=1693230090.262146, max_length=50),
        ),
        migrations.AlterField(
            model_name='brandverification',
            name='created_at',
            field=models.CharField(default=1693230090.259147, max_length=50),
        ),
        migrations.AddIndex(
            model_name='rolesforbrand',
            index=models.Index(fields=['role_name'], name='micro_brand_role_na_b0cb71_idx'),
        ),
    ]
